"""
    Looping your code with for

        Another kind of loop available in Python comes from the observation
            that sometimes it's more important to count the "turns" of the loop
            than to check the conditions.

        i = 0
        while i < 100:
            # do_something()
            i += 1

        Actually, the for loop is designed to do more complicated tasks - it can "browse" large
            collections of data item by item.

        for i in range(100):
            # do_something()
            pass
"""

for i in range(10):
    print("The value of i is currently", i)


"""
    NOTE

        - the loop has been executed ten times (it's the range() function's argument)
        - the last control variable's value is 9 (not 10, as it starts from 0, not from 1)

        the range() function accepts only integers as its arguments, and generates sequences of integers.
"""

for i in range(2, 8, 3):
    print("The value of i is currently", i)


"""
    The range() function may also accept three arguments - take a look at the code in the editor.

        The range() function may also accept three arguments

        The third argument is an increment - it's a value added to control the variable at every loop turn
             (as you may suspect, the default value of the increment is 1).

        The code above will print the following:
            The value of i is currently 2
            The value of i is currently 5

        Do you know why? The first argument passed to the range() function tells us what the starting
        The second argument tells the function where to stop the sequence
            (the function generates numbers up to the number indicated by the second argument, but does not include it).

        The third argument indicates the step, which actually means the difference between each number
            in the sequence of numbers generated by the function.

        NOTE

            If the set generated by the range() function is empty, the loop won't execute its body at all.

                for i in range(1, 1):
                    print("The value of i is currently", i)

            the range()'s second argument must be greater than the first. only if we have only two arguments,

"""

# Example 1

for i in range(2, 1):
    print("The value of i is currently", i)

# Example 2

power = 1
for expo in range(16):
    print("2 to the power of", expo, "is", power)
    power *= 2

# Go to LAB-6